baseURL = "https://labs.chansteven.com/"
languageCode = "en-us"
title = "Steven's Lab"
theme = "PaperMod"

[params]
  description = "A place for experiments and thoughts"
  author = "Steven Chan"
  
  # Social links
  social = [
    {name = "github", url = "https://github.com/chanstev"},
    {name = "linkedin", url = "https://linkedin.com/in/chansteven"}
  ]

  # PaperMod specific settings
  PaperMod = {
    themeColor = "blue"
    themeVariant = "auto"
    showBreadCrumbs = true
    showRightColumn = true
    showContentFooter = true
    showSummary = true
    showFullArticle = false
    showReadingTime = true
    showShareButtons = true
    showPostNavLinks = true
  }

[markup]
  goldmark = true
  [markup.goldmark.renderer]
    unsafe = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[menu]
  [[menu.main]]
    name = "Experiments"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Thoughts"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[build]
  # Build into docs directory for GitHub Pages
  publishDir = "docs"
