baseURL = "/"
languageCode = "en-us"
title = "Steven's Lab"
theme = "PaperMod"

[build]
publishDir = "docs"

[params]
  # Disable all PaperMod features
disableAnchoredHeadings = true
hideMeta = true
hideSummary = true

[outputFormats]
  [outputFormats.HTML]
    mediaType = "text/html"
    isPlainText = false
    isHTML = true
    charset = "UTF-8"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[server]
  port = 1313
  appendPort = false
