baseURL = "https://labs.chansteven.com/"
languageCode = "en-us"
title = "Steven's Lab"
theme = "PaperMod"

[build]
publishDir = "docs"

[params]
disableAnchoredHeadings = true
hideMeta = true
hideSummary = true

[outputFormats]
  [outputFormats.HTML]
    mediaType = "text/html"
    isPlainText = false
    isHTML = true
    charset = "UTF-8"
