baseURL = "https://labs.chansteven.com/"
languageCode = "en-us"
title = "Steven's Lab"

[build]
publishDir = "docs"

[module]
enable = true

[[module.imports]]
  path = "github.com/theNewDynamic/gohugo-theme-ananke"
