baseURL = "/"
languageCode = "en-us"
title = "Steven's Lab"
theme = "PaperMod"

[build]
publishDir = "docs"

[params]
  # Disable PaperMod features that might cause issues
  disableAnchoredHeadings = true
  hideMeta = true
  hideSummary = true

[server]
  port = 1313
  appendPort = false
