theme: jekyll-theme-minimal
title: Steven Chan Labs
description: A home for experiments of Steven Chan
baseurl: ""
url: "https://labs.chansteven.com"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  experiments:
    output: true
  thoughts:
    output: true

# Exclude from processing
exclude:
  - node_modules
  - vendor
  - .git
  - .github
  - src 