title: Steven's Lab
baseurl: ""
url: "https://labs.chansteven.com"

# Collections
collections:
  experiments:
    output: true
    permalink: /experiments/:path/
    default:
      layout: experiment
      title: ""
      description: ""
      tags: []
  thoughts:
    output: true
    permalink: /thoughts/:path/
    default:
      layout: thought
      title: ""
      description: ""
      tags: []

# Navigation
nav:
  - title: Experiments
    url: /
  - title: Thoughts
    url: /thoughts/
  - title: About
    url: /about/

# Social links
social:
  github: "chanstev"
  linkedin: "chansteven"

# Build settings
markdown: kramdown
theme: minima

# Exclude files
exclude:
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - .git
  - .github
  - .DS_Store

# Permalinks
permalink: pretty
  - README.md
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - .git
  - .github
  - .DS_Store
