name: Hugo CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # Install Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.120.4'  # Using a specific version that's known to work
          extended: true
      
      # Set up SSH for theme cloning
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "Host github.com" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  User git" >> ~/.ssh/config
      
      # Install theme
      - name: Install Theme
        run: |
          git clone git@github.com:panr/hugo-theme-quint.git themes/quint
      
      # Build the site
      - name: Build with Hugo
        run: hugo --minify
      
      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
